language:
  - ruby

services:
  - docker

before_install:
  - docker image build -t lorrenzofreemano/flasky:v1.0 .

deploy:
  - docker login --username "$DOCKERUSER" --password "$DOCKERPWD" 
  - docker image push lorrenzofreemano/flasky:v1.0
